# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('company_name', models.CharField(default='guest', max_length=40)),
                ('details', models.CharField(default='Application', max_length=10000)),
                ('user_name', models.CharField(default='guest', max_length=20)),
                ('application_text', models.CharField(max_length=100000, primary_key=True, serialize=False)),
                ('pay_expected', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('company_name', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=100000, primary_key=True, serialize=False)),
                ('pay', models.IntegerField(default=0)),
                ('deadline', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='JobProvider',
            fields=[
                ('company_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media/', width_field='width_field')),
                ('website_linked', models.URLField()),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('user_introduction', models.CharField(default='', max_length=20000)),
            ],
        ),
    ]
