# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='details',
            field=models.CharField(default='guest', max_length=10000),
        ),
    ]
