# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20160913_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='job_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='company_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='deadline',
            field=models.IntegerField(default=0),
        ),
    ]
