# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20160913_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_provider',
            new_name='JobProvider',
        ),
        migrations.RenameModel(
            old_name='job_seeker',
            new_name='JobSeeker',
        ),
    ]
