# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20160920_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='img',
            field=models.ImageField(blank=True, default='media/default.png', height_field='height_field', null=True, upload_to='media/', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_introduction',
            field=models.CharField(default='No Introduction Added', max_length=20000),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='website_linked',
            field=models.URLField(default='No Website Linked'),
        ),
    ]
