# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20160913_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='user_name',
            field=models.CharField(default=b'guest', max_length=20),
        ),
    ]
