# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_jobapplication_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='Application_text',
            new_name='application_text',
        ),
    ]
