# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_jobscompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobscompleted',
            name='details',
        ),
    ]
