# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_jobscompleted_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='deadline',
            field=models.IntegerField(),
        ),
    ]
