# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20160913_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField(default=0)),
                ('profile_img', models.ImageField(upload_to=b'')),
                ('website_linked', models.CharField(default=b'', max_length=100)),
                ('user_introduction', models.CharField(default=b'', max_length=20000)),
            ],
        ),
    ]
