# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='img',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=b'media/', width_field=b'width_field'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
