# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20160915_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='pay_expected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='deadline',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='pay',
            field=models.IntegerField(default=0),
        ),
    ]
