# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20160917_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(default=b'guest', max_length=40),
        ),
    ]
