# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_jobapplication_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(default='guest', max_length=40),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user_name',
            field=models.CharField(default='guest', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='jobprovider',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media/', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_introduction',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='website_linked',
            field=models.CharField(default='', max_length=100),
        ),
    ]
