# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20160919_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprovider',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
