# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20160919_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='website_linked',
            field=models.URLField(),
        ),
    ]
