# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20160919_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='details',
            field=models.ForeignKey(default=b'Null', on_delete=django.db.models.deletion.CASCADE, to='registration.JobDetails'),
        ),
    ]
