# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_text', models.CharField(max_length=100000)),
                ('status', models.BooleanField(default=10)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='job_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100000)),
                ('pay', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField(verbose_name=b'Date to complete the project till')),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='job_application',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content_Scriber.job_details'),
        ),
    ]
